### PR TITLE
Alwin and Ash Greetings

### PR DESCRIPTION
**Pull request by AshTS**
Add the generate name functions and code to add those strings to the output in `Hello.java`.

### CODE REVIEW

**Review by trinc005 — DISMISSED** [review]
Everything looks correct.

**Review by GregoryPetterson — DISMISSED** [review]
Looks good!

**Review by lor00148 — APPROVED** [review]
The string building passes the eyetest. It's all in alphabetical order. Construction methods have good names and follow the standard naming method.

**Review by trinc005 — APPROVED** [review]
Everything looks good. Just wondering why there are two Alwins and Ashes.

**Pull request merged**
