### PR TITLE
Finished Editing

### PR DESCRIPTION
**Pull request by trinc005**
Co-authored-by: Gregory <pet03356@morris.umn.edu>

### CODE REVIEW

**Review by AshTS — COMMENTED** [review]
The functions have been added, the style is consistent, and are appended to the builder in the correct order, everything looks correct!

**Review by AshTS — APPROVED** [review]
The functions have been added, the style is consistent, and are appended to the builder in the correct order, everything looks correct!

**Comment by NoahKilkerStudent** [comment]
looks good, feel free to push to main /jaydon

**Review by lor00148 — APPROVED** [review]
Everything looks good. The string builder looks good and so do the constructors for the new names.

**Review by NoahKilkerStudent — APPROVED** [review]

**Pull request merged**
